import { Inter } from "next/font/google";
import "./globals.css";
import "@/assets/style/nav-style.css";
import ScrollButton from "@/components/master/ScrollToTop";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <ScrollButton />
        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
